#%RAML 1.0
title: Report Service
version: 1.0.0
protocols:
  - HTTP
baseUri: https://www.hmislynk.com/hmis-report-service/rest
mediaType: application/json
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include security-schemes/oauth_2_0.raml
types:
  reports: !include reports.json
  report_id: !include report_id.json
  reports: !include reports.json
  report_ids: !include report_ids.json

/reports:
  get:
    description: gets all the reports for a user.
    responses:
      '200':
        body:
          application/json:
            example: !include report_ids_example.json
      '401':
        body:
          application/json:
            example:
              message: ' Unauthorized'
            required: false
      '500':
        body:
          application/json:
            example:
              errorMessage: internal server error
            required: false
    queryParameters:
      inactive:
        required: false
        description: Filter the list of bulk upload.
        example: true
        type: boolean
  post:
    description: Create a report.
   Example url :
   hmis-report-service/rest/reports = Add a report
    body:
      application/json:
        type: report_id
        example: !include report_example.json
    responses:
      '200':
        body:
          application/json:
            example: !include report_id_example.json
      '401':
        body:
          application/json:
            example:
              message: ' Unauthorized'
            required: false
      '500':
        body:
          application/json:
            example:
              message: Resource not foundx
            required: false

  /{report_id}:
    uriParameters:
      report_id: {}
    displayName: retreive
    description: 'Get a report config by id'
    get:
      description: Get a report config by id.
      responses:
        '200':
          body:
            application/json:
              example: !include report_id_example.json
        '401':
          body:
            application/json:
              example:
                message: ' Unauthorized'
              required: false
        '500':
          body:
            application/json:
              example:
                errorMessage: internal server error
              required: false
