openapi: 3.0.0
info:
  title: HMIS User Service
  version: 1.0.0
servers:
  - url: 'https://www.hslynk.com/hmis-report-service/rest'
paths:
  /reports:
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: >
        It creates request a report belonging to a project group by providing
        1) Name
        2) reportLevel
        3) reportType
        4) startDate
        5) endDate
        6) projectIds

        The user must have "CREATE_REPORT_CONFIG" permission to use this API
      operationId: POST_reports
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To get all the reports created by the user.
      operationId: GET_reports
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name: startIndex
          in: query
          schema:
            default: '0'
            type: string
        - name: maxItems
          in: query
          schema:
            default: '30'
            type: string
  '/reports/{reportId}':
    get:
      responses:
        '200':
          description: |
            Report a report by id.
          content:
            application/json:
              schema:
                type: object
        '403':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: |
        Gets (aka reads or retrieves) a specific report. <BR><br>
        GET /reports/{username}
        <b>
      operationId: GET_reports-reportId
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
      parameters:
        - name: reportId
        in: path
        required: true
        schema:
          type: string
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    oauth_2_0:
      description: |
        The HMIS API supports OAuth 2.0 for authenticating all API requests.
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://hmislynk.com/hmis-authorization-service/rest/token'
          scopes:
            user: ''
            administrator: ''
  links: {}
  callbacks: {}
